version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend
    overwrite: yes

permissions:
  - object: /home/ec2-user/backend
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user