version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myfoodmap-server
    overwrite: yes

permissions:
  - object: /home/ubuntu/myfoodmap-server
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu